Fix Forgejo kustomize code

diff --git a/kubernetes/apps/git-server/forgejo/secret-config-scripts.yaml b/kubernetes/apps/git-server/forgejo/secret-config-scripts.yaml
--- a/kubernetes/apps/git-server/forgejo/secret-config-scripts.yaml
+++ b/kubernetes/apps/git-server/forgejo/secret-config-scripts.yaml
@@ -12,8 +12,19 @@ stringData:
     #!/usr/bin/env bash
     set -euo pipefail
 
-    git_project_name=GITEA
-    # git_project_name=FORGEJO
+    export GITEA_APP_INI="${FORGEJO_APP_INI}"
+    if [[ -z "${FORGEJO_APP_INI}" ]]; then
+      export GITEA_APP_INI="${FORGEJO_APP_INI}"
+    fi
+    if [[ -z "${FORGEJO_WORK_DIR}" ]]; then
+      export GITEA_WORK_DIR="${FORGEJO_WORK_DIR}"
+    fi
+    if [[ -z "${FORGEJO_TEMP}" ]]; then
+      export GITEA_TEMP="${FORGEJO_TEMP}"
+    fi
+    if [[ -z "${FORGEJO_CUSTOM}" ]]; then
+      export GITEA_CUSTOM="${FORGEJO_CUSTOM}"
+    fi
 
     function env2ini_log() {
       printf "${1}\n"
@@ -38,17 +49,24 @@ stringData:
 
       env2ini_log "  + '${setting}'"
 
-      local value="$(echo "${line}" | awk -F '=' '{print $1}' | xargs echo -n)"
+      local value=''
+      local regex="^${setting}(\s*)=(\s*)(.*)"
+      if [[ $line =~ $regex ]]; then
+        value="${BASH_REMATCH[3]}"
+      else
+        env2ini::log '  ! invalid setting'
+        exit 1
+      fi
 
       if [[ -z "${section}" ]]; then
-        export "${git_project_name}____${setting^^}"="${value}"                           # '^^' makes the variable content uppercase
+        export "FORGEJO_____${setting^^}"="${value}"                           # '^^' makes the variable content uppercase
         return
       fi
 
       local masked_section="${section//./_0X2E_}"                            # '//' instructs to replace all matches
       masked_section="${masked_section//-/_0X2D_}"
 
-      export "${git_project_name}__${masked_section^^}__${setting^^}"="${value}"        # '^^' makes the variable content uppercase
+      export "FORGEJO___${masked_section^^}__${setting^^}"="${value}"        # '^^' makes the variable content uppercase
     }
 
     function env2ini_reload_preset_envs() {
@@ -72,7 +90,14 @@ stringData:
 
         env2ini_log "  + '${setting}'"
 
-        local value="$(echo "${line}" | awk -F '=' '{print $1}' | xargs echo -n)"
+        local value=''
+        local regex="^${setting}(\s*)=(\s*)(.*)"
+        if [[ $line =~ $regex ]]; then
+          value="${BASH_REMATCH[3]}"
+        else
+          env2ini::log '  ! invalid setting'
+          exit 1
+        fi
 
         export "${setting^^}"="${value}"                           # '^^' makes the variable content uppercase
       done < "/tmp/existing-envs"
@@ -116,19 +141,19 @@ stringData:
       #   - initially used to set up Gitea
       # Anyway, they won't harm existing app.ini files
 
-      export ${git_project_name}__SECURITY__INTERNAL_TOKEN=$(forgejo generate secret INTERNAL_TOKEN)
-      export ${git_project_name}__SECURITY__SECRET_KEY=$(forgejo generate secret SECRET_KEY)
-      export ${git_project_name}__OAUTH2__JWT_SECRET=$(forgejo generate secret JWT_SECRET)
-      export ${git_project_name}__SERVER__LFS_JWT_SECRET=$(forgejo generate secret LFS_JWT_SECRET)
+      export FORGEJO___SECURITY__INTERNAL_TOKEN=$(forgejo generate secret INTERNAL_TOKEN)
+      export FORGEJO___SECURITY__SECRET_KEY=$(forgejo generate secret SECRET_KEY)
+      export FORGEJO___OAUTH2__JWT_SECRET=$(forgejo generate secret JWT_SECRET)
+      export FORGEJO___SERVER__LFS_JWT_SECRET=$(forgejo generate secret LFS_JWT_SECRET)
 
       env2ini_log "...Initial secrets generated\n"
     }
 
-    env2ini_log "=== Forjejo still uses Gitea variables ===\n"
-    source <(printenv | awk '{ if (sub(/^FORGEJO_/, "GITEA_") > 0) { split($0, kv, "="); print "export "kv[1]"=\x22"kv[2]"\x22" } }')
+    # env2ini_log "=== Forjejo still uses Gitea variables ===\n"
+    # source <(printenv | awk '{ if (sub(/^FORGEJO_/, "GITEA_") > 0) { split($0, kv, "="); print "export "kv[1]"=\x22"kv[2]"\x22" } }')
 
     # save existing envs prior to script execution. Necessary to keep order of preexisting and custom envs
-    env | (grep -e '^'"${git_project_name}"'__' || [[ $? == 1 ]]) > /tmp/existing-envs
+    env | (grep -e "^FORGEJO__" || [[ $? == 1 ]]) > /tmp/existing-envs
 
     # MUST BE CALLED BEFORE OTHER CONFIGURATION
     env2ini_generate_initial_secrets
@@ -142,8 +167,8 @@ stringData:
     env2ini_log "=== All configuration sources loaded ===\n"
 
     # safety to prevent rewrite of secret keys if an app.ini already exists
-    if [ -f "${git_project_name}_APP_INI" ]; then
+    if [ -f "${FORGEJO_APP_INI}" ]; then
       env2ini_log 'An app.ini file already exists.'
     fi
 
-    environment-to-ini -o "${git_project_name}_APP_INI"
+    environment-to-ini -o "${FORGEJO_APP_INI}"
