Use NO_COLOR in scripts to suppress colors and emoji

diff --git a/project-management b/project-management
--- a/project-management
+++ b/project-management
@@ -13,22 +13,55 @@ generated_project_path="${project_root_path:?}/${generated_project_relative_path
 valid_architectures=( amd64 x86_64 arm64 aarch64 )
 valid_orchestrators=( fake multipass vbox )
 
+: ${NO_COLOR:=0}
+if [[ -z ${NO_COLOR+notset} ]] || [ "${NO_COLOR}" == "0" ]; then
+  bold_text=$(tput bold)
+  bad_result_text=$(tput setaf 1)
+  good_result_text=$(tput setaf 2)
+  highlight_text=$(tput setaf 3)
+  info_text=$(tput setaf 4)
+  gray_text=$(tput setaf 8)
+  reset_text=$(tput sgr 0)
+  status_success=✅
+  status_error=❌
+  status_warning=⚠️
+  status_info=ℹ️
+  status_waiting=💤
+  status_action=⚙️
+else
+  bold_text=''
+  bad_result_text=''
+  good_result_text=''
+  highlight_text=''
+  info_text=''
+  gray_text=''
+  reset_text=''
+  status_success='[SUCCESS]'
+  status_error='[ERROR]'
+  status_warning='[WARNING]'
+  status_info='[INFO]'
+  status_waiting='[WAITING]'
+  status_action='[ACTION]'
+fi
+
 __usage=$(
 	cat <<-HELPMSG
-		$(tput setaf 2)Usage:$(tput sgr0) $(tput bold)$0 [OPTIONS]$(tput sgr0)
+		${highlight_text}Usage:${reset_text} ${bold_text}$0 [OPTIONS]${reset_text}
 
-		$(tput setaf 3)$(tput bold)Manage instances provisioning.$(tput sgr0)
+		${highlight_text}${bold_text}Manage instances provisioning.${reset_text}
 
 		Options:
-		  -a, --all                   $(tput setaf 8)Run all tasks to setup instances (in order: generate bootstrap wrap-up provision)$(tput sgr0)
-		  -o, --orchestrator          $(tput setaf 8)Select orchestrator for instances management scripts generator (default: '${generator_orchestrator}')$(tput sgr0)
-		  -m, --machine-architecture  $(tput setaf 8)Host architecture (default: '${host_architecture}' using 'uname -m')$(tput sgr0)
-		  -g, --generate              $(tput setaf 8)Generate instances management scripts$(tput sgr0)
-		  -b, --bootstrap             $(tput setaf 8)Bootstrap project network and instances using generated scripts$(tput sgr0)
-		  -w, --wrap-up               $(tput setaf 8)Wrap-up project basic setup using generated scripts$(tput sgr0)
-		  -p, --provision             $(tput setaf 8)Provision instances using generated scripts$(tput sgr0)
-		  -d, --delete                $(tput setaf 8)Delete instances and local project data using generated scripts$(tput sgr0)
-		  -h, --help                  $(tput setaf 8)This help$(tput sgr0)
+		  -a, --all                   ${gray_text}Run all tasks to setup instances (in order: generate bootstrap wrap-up provision)${reset_text}
+		  -o, --orchestrator          ${gray_text}Select orchestrator for instances management scripts generator (default: '${generator_orchestrator}')${reset_text}
+		  -m, --machine-architecture  ${gray_text}Host architecture (default: '${host_architecture}' using 'uname -m')${reset_text}
+		  -g, --generate              ${gray_text}Generate instances management scripts${reset_text}
+		  -b, --bootstrap             ${gray_text}Bootstrap project network and instances using generated scripts${reset_text}
+		  -w, --wrap-up               ${gray_text}Wrap-up project basic setup using generated scripts${reset_text}
+		  -p, --provision             ${gray_text}Provision instances using generated scripts${reset_text}
+		  -d, --delete                ${gray_text}Delete instances and local project data using generated scripts${reset_text}
+		  -h, --help                  ${gray_text}This help${reset_text}
+		Environment variables:
+		  NO_COLOR                    ${gray_text}suppress colorized output${reset_text}
 	HELPMSG
 )
 
@@ -43,7 +76,7 @@ fi
 
 check_dependency() {
   if ! [ -x "$(command -v "$1")" ]; then
-    echo -e "$(tput setaf 2)Error: $(tput bold)$1$(tput sgr0)$(tput setaf 2) is not installed.$(tput sgr0)" >&2
+    echo -e "${bad_result_text}Error: ${bold_text}$1${reset_text}${bad_result_text} is not installed.${reset_text}" >&2
     exit 1
   fi
 }
@@ -51,12 +84,13 @@ check_dependency() {
 generate_ansible_ssh_keys() {
   ansible_ssh_key_file="${generated_project_relative_path:?}/assets/.ssh/id_ed25519"
   if [ -f "${project_root_path:?}/${ansible_ssh_key_file:?}" ]; then
-    echo "Using existing SSH keys for ansible ✅"
+    echo " ${status_info} Using existing SSH keys for ansible."
   else
     check_dependency 'ssh-keygen'
-    echo "Generating SSH keys for ansible ..."
+    echo " ${status_action} Generating SSH keys for ansible ..."
     mkdir -p "$(dirname "${project_root_path:?}/${ansible_ssh_key_file:?}")"
     ssh-keygen -t ed25519 -C "automator@iam-demo.test" -f "${project_root_path:?}/${ansible_ssh_key_file:?}" -q -N ""
+    echo " ${status_success} SSH keys for ansible generated."
   fi
 }
 
@@ -64,15 +98,15 @@ generate_bootstrap_scripts() {
   check_dependency 'jsonnet'
   project_config_file="${project_generator_relative_path:?}/config/config.libsonnet"
   if [ -f "${project_root_path:?}/${project_config_file:?}" ]; then
-    echo "Using existing project config '$(tput bold)${project_config_file:?}$(tput sgr0)' ✅"
+    echo " ${status_info} Using existing project config '${bold_text}${project_config_file:?}${reset_text}'"
   else
-    echo "Missing config.libsonnet"
-    echo "Copying config.libsonnet.${generator_orchestrator:?}.example to '${project_config_file:?}'"
+    echo " ${status_info} Missing config.libsonnet"
+    echo " ${status_action} Copying config.libsonnet.${generator_orchestrator:?}.example to '${project_config_file:?}'"
     cp "${project_generator_path:?}/config/config.libsonnet.${generator_orchestrator:?}.example" \
       "${project_root_path:?}/${project_config_file:?}"
   fi
-  echo "Using orchestrator: $(tput bold)${generator_orchestrator}$(tput sgr0)"
-  echo "Using host_architecture: $(tput bold)${host_architecture}$(tput sgr0)"
+  echo " ${status_info} Using orchestrator: ${bold_text}${generator_orchestrator}${reset_text}"
+  echo " ${status_info} Using host_architecture: ${bold_text}${host_architecture}${reset_text}"
   jsonnet --create-output-dirs \
     --multi "${generated_project_path}" \
     --ext-str project_root_path="${project_root_path}" \
@@ -155,7 +189,7 @@ while [ $# -gt 0 ] && [ "$1" != "" ]; do
       exit 0
       ;;
     *)
-      printf "$(tput setaf 1)Unexpected argument: $(tput bold)%s$(tput sgr0)\n" "$1" >&2
+      printf "${bad_result_text}Unexpected argument: ${bold_text}%s${reset_text}\n" "$1" >&2
       usage
       exit 1
       ;;
@@ -163,12 +197,12 @@ while [ $# -gt 0 ] && [ "$1" != "" ]; do
 done
 
 if [[ ! " ${valid_architectures[*]} " =~ " ${host_architecture} " ]]; then
-  printf "$(tput setaf 1)Error: 'host_architecture' must be one of: $(tput bold)${valid_architectures[*]}$(tput sgr0)\n" >&2
+  printf "${bad_result_text}Error: 'host_architecture' must be one of: ${bold_text}${valid_architectures[*]}${reset_text}\n" >&2
   exit 1
 fi
 
 if [[ ! " ${valid_orchestrators[*]} " =~ " ${generator_orchestrator} " ]]; then
-  printf "$(tput setaf 1)Error: 'orchestrator' must be one of: $(tput bold)${valid_orchestrators[*]}$(tput sgr0)\n" >&2
+  printf "${bad_result_text}Error: 'orchestrator' must be one of: ${bold_text}${valid_orchestrators[*]}${reset_text}\n" >&2
   exit 1
 fi
 
@@ -178,35 +212,35 @@ if $delete; then
 fi
 
 if $generate; then
-  echo "$(tput bold)$(tput setaf 2) - Creating instances setup scripts ... - $(tput sgr0)"
+  echo "${status_info}${bold_text}${highlight_text} - Creating instances setup scripts ... - ${reset_text}"
   generate_ansible_ssh_keys
   generate_bootstrap_scripts
-  echo "$(tput bold)$(tput setaf 2) - Instances setup scripts generated ✅ - $(tput sgr0)"
+  echo "${status_success}${bold_text}${highlight_text} - Instances setup scripts generated - ${reset_text}"
 fi
 if $bootstrap; then
-  echo "$(tput bold)$(tput setaf 2) - Starting project network and instances creation ... - $(tput sgr0)"
+  echo "${status_info}${bold_text}${highlight_text} - Starting project network and instances creation ... - ${reset_text}"
   project_bootstrap
-  echo "$(tput bold)$(tput setaf 2) - Project network and instances creation done ✅ - $(tput sgr0)"
+  echo "${status_success}${bold_text}${highlight_text} - Project network and instances creation done - ${reset_text}"
 fi
 if $wrap_up; then
-  echo "$(tput bold)$(tput setaf 2) - Running project wrap-up ... - $(tput sgr0)"
+  echo "${status_info}${bold_text}${highlight_text} - Running project wrap-up ... - ${reset_text}"
   instances_wrap_up
-  echo "$(tput bold)$(tput setaf 2) - Project wrap-up done ✅ - $(tput sgr0)"
+  echo "${status_success}${bold_text}${highlight_text} - Project wrap-up done - ${reset_text}"
 fi
 if $provision; then
-  echo "$(tput bold)$(tput setaf 2) - Starting project instances provisioning ... - $(tput sgr0)"
+  echo "${status_info}${bold_text}${highlight_text} - Starting project instances provisioning ... - ${reset_text}"
   project_provisioning
-  echo "$(tput bold)$(tput setaf 2) - Project instances provisioning done ✅ - $(tput sgr0)"
+  echo "${status_success}${bold_text}${highlight_text} - Project instances provisioning done - ${reset_text}"
 fi
 
-echo "$(tput bold)$(tput setaf 2) - All done ✅ - $(tput sgr0)"
+echo "${status_success}${bold_text}${highlight_text} - All done - ${reset_text}"
 echo
-echo "$(tput setaf 3)Project root path: $(tput bold)${project_root_path}$(tput sgr0)"
+echo " ${highlight_text}Project root path: ${bold_text}${project_root_path}${reset_text}"
 
 if $bootstrap || $wrap_up || $provision; then
   echo
-  echo "$(tput setaf 3)To ssh into an instance use $(tput bold)./instance-shell.sh <instance-name>$(tput sgr0) from the generated folder."
-  echo "  $(tput bold)$(tput setaf 5)Example:$(tput sgr0)"
-  echo "  $(tput bold)cd ${generated_project_path}$(tput sgr0)"
-  echo "  $(tput bold)./instance-shell.sh ansible-controller$(tput sgr0)"
+  echo "${highlight_text}To ssh into an instance use ${bold_text}./instance-shell.sh <instance-name>${reset_text} from the generated folder."
+  echo "  ${bold_text}Example:${reset_text}"
+  echo "  ${bold_text}cd ${generated_project_path}${reset_text}"
+  echo "  ${bold_text}./instance-shell.sh ansible-controller${reset_text}"
 fi
